---
- name: Get current state
  k8s_info:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: '{{ meta.name }}'
    namespace: '{{ operator_namespace }}'
  register: resource_state

- operator_sdk.util.k8s_status:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: "{{ meta.name }}"
    namespace: "{{ operator_namespace }}"
    status:
      state: Building
      complete: false
  when: resource_state.resources[0].status.state is not defined

- name: Get current state - If it has changed
  k8s_info:
    api_version: ripsaw.cloudbulldozer.io/v1alpha1
    kind: Benchmark
    name: '{{ meta.name }}'
    namespace: '{{ operator_namespace }}'
  register: resource_state

- block:
  - name: start kernel cache dropper
    k8s:
      src: "/opt/kernel_cache_dropper/kernel-cache-drop-daemonset.yaml"
    when: workload_args.drop_cache_kernel is defined

- block:
  - name: Provide path for fio - PV
    set_fact:
      fio_path: /mnt/pvc
    when: workload_args.storageclass is defined

  - name: Provide path for fio - No PV
    set_fact:
      fio_path: /tmp
    when: workload_args.storageclass is not defined

  - name: Generate fio test
    k8s:
      definition: "{{ lookup('template', 'configmap.yml.j2') | from_yaml }}"

  - name: Create PVC(s)
    k8s:
      definition:
        kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          name: "claim-{{ item }}-{{ trunc_uuid }}"
          namespace: '{{ operator_namespace }}'
          annotations:
             volume.beta.kubernetes.io/storage-class: "{{ workload_args.storageclass }}"
        spec:
          accessModes:
            - "{{ workload_args.pvcaccessmode | default('ReadWriteOnce') }}"
          volumeMode: "{{ workload_args.pvcvolumemode | default('Filesystem') }}"
          resources:
            requests:
              storage: "{{ workload_args.storagesize }}"
    with_sequence: start=1 count={{ workload_args.servers|default('1')|int }}
    when: workload_args.storageclass is defined

  - name: Start FIO Server(s)
    k8s:
      definition: "{{ lookup('template', 'servers.yaml') | from_yaml }}"
    when: workload_args.servers|default('1')|int > 0 and (workload.args.kind | default('pod')) == "pod"
    with_sequence: start=1 count={{ workload_args.servers|default('1')|int }}

  - name: Start FIO Server(s) VM
    k8s:
      definition: "{{ lookup('template', 'server_vm.yml.j2') | from_yaml }}"
    when: workload_args.servers|default('1')|int > 0 and (workload.args.kind | default('pod')) == "vm"
    with_sequence: start=1 count={{ workload_args.servers|default('1')|int }}

  - operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: StartingServers
        complete: false

  when: resource_state.resources[0].status.state == "Building"

- block :

  - name: Capture pod list
    k8s_info:
      kind: Pod
      api_version: v1
      namespace: '{{ operator_namespace }}'
      label_selectors:
        - app = fio-benchmark-{{ trunc_uuid }}
    register: server_pods

  - operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: WaitingForCacheDroppers
        complete: false
    when : "workload_args.servers|default('1')|int == (server_pods | json_query('resources[].status.podIP')|length) and workload_args.servers|default('1')|int == (server_pods | json_query('resources[].status[]')|selectattr('phase','match','Running')|list|length) and resource_state.resources[0].status.state == 'StartingServers'"

  - name: Create IP list and nodes
    set_fact:
      pod_details: "{{ pod_details|default({}) | combine({item.status.podIP: item.spec.nodeName}) }}"
    with_items: "{{ server_pods.resources }}"

  when: (workload.args.kind | default('pod')) == "pod"


- block:
  - name: get kernel cache dropper pods
    k8s_facts:
      kind: Pod
      label_selectors:
        - name = kernel-cache-dropper
      namespace: "{{ operator_namespace }}"
    register: kcache_drop_pod_list

  - name: put ip list into a var
    set_fact:
      iplst: |
         {% for item in kcache_drop_pod_list.resources %}
         {{ item.status.podIP }}
         {% endfor %}

  - name: delete old configmap
    k8s:
      kind: ConfigMap
      name: kernel.cache.drop.pod.set
      namespace: "{{ operator_namespace }}"
      state: absent

  - name: apply kcache_drop_pod_ip configmap
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: kernel.cache.drop.pod.set
          namespace: "{{ operator_namespace }}"
        data:
          ips: "{{ iplst }}"

  - name: show kernel cache dropper pods requested
    when: kcache_drop_pod_list.resources | length > 0
    shell: "echo {{ kcache_drop_pod_list.resources | length }}"
    register: kcache_drop_pods_requested


  - operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: StartingClient
        complete: false
    when : "workload_args.drop_cache_kernel is not defined or kcache_drop_pod_list.resources | length == kcache_drop_pods_requested.stdout | int"
  when: resource_state.resources[0].status.state == "WaitingForCacheDroppers"


- block :

  - name: Capture pod list
    k8s_info:
      kind: VirtualMachineInstance
      api_version: kubevirt.io/v1alpha3
      namespace: '{{ operator_namespace }}'
      label_selectors:
        - app = fio-benchmark-{{ trunc_uuid }}
    register: server_pods

  - operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: StartingClient
        complete: false
    when : "workload_args.servers|default('1')|int == (server_pods | json_query('resources[].status.interfaces[].ipAddress')|length) and workload_args.servers|default('1')|int == (server_pods | json_query('resources[].status[]')|selectattr('phase','match','Running')|list|length) and resource_state.resources[0].status.state == 'StartingServers'"

  - name: Create IP list and nodes
    set_fact:
      pod_details: "{{ pod_details|default({}) | combine({item.status.interfaces[0].ipAddress: item.status.nodeName}) }}"
    with_items: "{{ server_pods.resources }}"

  when: (workload.args.kind | default('pod')) == "vm"

- block:

  - name: Generate fio hosts
    k8s:
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: fio-hosts-{{ trunc_uuid }}
          namespace: '{{ operator_namespace }}'
        data:
          hosts: |
            {% for ip in pod_details.keys() %}
            {{ ip }}
            {% endfor %}

  - name: (VM) Wait for fio server port to be open - signaling fio server boot up
    wait_for:
      host: "{{ item }}"
      port: 8765
    when: (workload.args.kind | default('pod')) == "vm"
    with_items: "[{% for ip in pod_details.keys() %}'{{ ip }}', {% endfor %}]"

  - name: fetch configmap info for kernel cache drop ips
    k8s_info:
      kind: ConfigMap
      namespace: '{{ operator_namespace }}'
      name: kernel.cache.drop.pod.set
    register: fetched_kcache_pods

  - name: set up kernel cache_drop ips
    set_fact:
      kcache_drop_pod_ips: "{{ fetched_kcache_pods.resources[0].data.ips }}"

  - name: Start FIO Client
    k8s:
      definition: "{{ lookup('template', 'client.yaml') | from_yaml }}"

  - operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: Running
        complete: false

  when: resource_state.resources[0].status.state == "StartingClient"

- block:
  - name: Capture Client pod list
    k8s_info:
      kind: Pod
      api_version: v1
      namespace: '{{ operator_namespace }}'
      label_selectors:
        - app = fiod-client-{{ trunc_uuid }}
    register: client_pods

  - operator_sdk.util.k8s_status:
      api_version: ripsaw.cloudbulldozer.io/v1alpha1
      kind: Benchmark
      name: "{{ meta.name }}"
      namespace: "{{ operator_namespace }}"
      status:
        state: Complete
        complete: true
    when : "client_pods|json_query('resources[].status[]')|selectattr('phase','match','Succeeded')|list|length > 0 "

  when: resource_state.resources[0].status.state == "Running"
