apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benchmark-operator-kube
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
    - subresources.kubevirt.io
  resources:
    - virtualmachineinstances/console
    - virtualmachineinstances/vnc
  verbs:
    - get
- apiGroups:
    - kubevirt.io
  resources:
    - virtualmachineinstances
    - virtualmachines
    - virtualmachineinstancepresets
    - virtualmachineinstancereplicasets
  verbs:
    - get
    - delete
    - create
    - update
    - patch
    - list
    - watch
    - deletecollection
- apiGroups: [""]
  resources:
    - configmaps
  resourceNames:
    - kubevirt-config
  verbs:
    - update
    - get
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
- kind: ServiceAccount
  name: benchmark-operator
  namespace: my-ripsaw
